<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Includes -->
  <xacro:include filename="$(find hardware_navigation)/urdf/material.xacro" />
  <xacro:include filename="$(find hardware_navigation)/urdf/macros.xacro" />

  <!-- Base Properties -->
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="base_length" value="1.0"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="base_mass" value="8"/>

  <!-- Wheel Properties -->
  <xacro:property name="wheel_radius" value="0.14"/>
  <xacro:property name="wheel_separation" value="0.6"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="wheel_mass" value="2"/>
  <xacro:property name="wheel_xoff" value="0.35"/>
  <xacro:property name="wheel_yoff" value="0.08"/>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius + 0.06) + 0.005}" rpy="0 0 0"/>
  </joint>

  <!-- Robot Base -->
  <link name="base_link">
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${base_mass}" w="${base_width}" d="${base_length}" h="${base_height}"/>
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Mecanum Wheel Macro -->
  <xacro:macro name="wheel" params="prefix side x_reflect y_reflect">
    <link name="${prefix}${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_gray">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0" ixz="0"
          iyy="${(wheel_mass/2.0) * (wheel_radius*wheel_radius)}" iyz="0"
          izz="${(wheel_mass/12.0) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}${side}_wheel_joint" type="continuous">
      <axis xyz="0 1 0"/>
      <parent link="base_link"/>
      <child link="${prefix}${side}_wheel_link"/>
      <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (wheel_separation / 2 + wheel_yoff)} ${-wheel_radius}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}${side}_wheel_link">
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>0.0</mu2>
          </ode>
        </friction>
      </surface>
      <visual>
        <material>
          <ambient>0.2 0.2 0.2 1.0</ambient>
          <diffuse>0.2 0.2 0.2 1.0</diffuse>
          <specular>0.2 0.2 0.2 1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>
  </xacro:macro>

  <!-- Instantiate 4 Wheels -->
  <xacro:wheel prefix="" side="front_left"  x_reflect="1"  y_reflect="1"/>
  <xacro:wheel prefix="" side="front_right" x_reflect="1"  y_reflect="-1"/>
  <xacro:wheel prefix="" side="back_left"   x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="" side="back_right"  x_reflect="-1" y_reflect="-1"/>

</robot>
