<?xml version="1.0"?>
<robot name="cart" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Includes -->
  <xacro:include filename="$(find cart_navigation)/urdf/material.xacro"/>
  <xacro:include filename="$(find cart_navigation)/urdf/macros.xacro"/>
  <xacro:include filename="$(find cart_navigation)/urdf/lidar.xacro"/>
  <xacro:include filename="$(find cart_navigation)/urdf/4w_control.gazebo"/>

  <!-- base_Properties -->
  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_length" value="1.0"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="base_mass" value="4"/>
  <!-- wheel_Properties -->
  <xacro:property name="wheel_radius" value="0.12"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="wheel_xoff" value="0.35"/>
  <xacro:property name="wheel_ygap" value="0.08"/>
  <!-- Stand Panel Properties -->
  <xacro:property name="panel_width" value="0.3"/>
  <xacro:property name="panel_length" value="0.1"/>
  <xacro:property name="panel_height" value="0.7"/>
  <xacro:property name="panel_mass" value="0.5"/>
  <xacro:property name="panel_x" value="-0.45"/>
  <xacro:property name="panel_y" value="0.0"/>
  <xacro:property name="panel_z" value="0.4"/>
 <!-- lidar Properties -->
  <xacro:property name="lidar_x" value="0.3"/>
  <xacro:property name="lidar_y" value="0.0"/>
  <xacro:property name="lidar_z" value="0.08"/>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0.0 0.0 ${-(wheel_radius + 0.06) + 0.005}" rpy="0 0 0"/>
</joint>

  <!-- Base -->
  <link name="base_link">
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${base_mass}" w="${base_width}" h="${base_height}" d="${base_length}"/>
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- stand panel -->
  <xacro:macro name="stand_panel" params="name parent_link">
    <link name="${name}">
      <visual>
        <geometry>
          <box size="${panel_length} ${panel_width} ${panel_height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <geometry>
          <box size="${panel_length} ${panel_width} ${panel_height}"/>
        </geometry>
      </collision>
      <xacro:box_inertia m="${panel_mass}" w="${panel_width}" h="${panel_height}" d="${panel_length}"/>
    </link>
    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}"/>
      <origin xyz="${panel_x} ${panel_y} ${panel_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="side x_reflect y_reflect">
    <link name="${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${side}_wheel_link"/>
      <!-- <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width/ 2 + wheel_ygap)} ${-wheel_radius}" rpy="0 0 0"/> -->
      <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width/ 2 + wheel_ygap)} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate wheels -->
  <xacro:wheel side="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel side="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel side="back_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel side="back_right" x_reflect="-1" y_reflect="-1"/>

  <!-- Instantiate stand panel -->
  <xacro:stand_panel name="stand_panel" parent_link="base_link"/>

  <!-- Instantiate lidar -->
  <xacro:lidar_sensor
    parent="base_link"
    frame_id="laser_frame"
    xyz_offset="${lidar_x} ${lidar_y} ${lidar_z}"
    rpy_offset="0 0 0"/>
</robot>
