<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="lidar_sensor" params="
    prefix:=''
    parent:='base_link'
    frame_id:='laser_frame'
    xyz_offset
    rpy_offset
    lidar_width:=0.03
    lidar_height:=0.03
    mass:=0.085
    color:='red'
    update_rate:=10
    ray_count:=360
    min_angle:='-3.14159'
    max_angle:='3.14159'
    min_range:='0.20'
    max_range:='30.0'
    range_resolution:='0.013'
    topic_name:='scan'
    always_on:=true
    visualize:=false
    enable_collision:=false">

    <link name="${prefix}${frame_id}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lidar_width / 2}" length="${lidar_height}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <xacro:if value="${enable_collision}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${lidar_width / 2}" length="${lidar_height}"/>
          </geometry>
        </collision>
      </xacro:if>

      <xacro:cylinder_inertia m="${mass}" r="${lidar_width / 2}" h="${lidar_height}"/>
    </link>

    <joint name="${prefix}${frame_id}_joint" type="fixed">
      <parent link="${prefix}${parent}"/>
      <child link="${prefix}${frame_id}"/>
      <origin xyz="${xyz_offset}" rpy="${rpy_offset}"/>
    </joint>

    <gazebo reference="${prefix}${frame_id}">
      <sensor name="${prefix}lidar_sensor" type="gpu_lidar">
        <topic>${topic_name}</topic>
        <update_rate>${update_rate}</update_rate>
        <always_on>${always_on}</always_on>
        <visualize>${visualize}</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>${ray_count}</samples>
              <resolution>1</resolution>
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
            <vertical>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </vertical>
          </scan>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>${range_resolution}</resolution>
          </range>
        </ray>
        <gz_frame_id>${prefix}${frame_id}</gz_frame_id>
      </sensor>
    </gazebo>
  </xacro:macro>

</robot>
